export interface LoginData {
    correo: string;
    password:string;
}


export interface RegisterData {
    nombre:string;
    correo: string;
    password:string;
}

export interface LoginResponse {
    usuario: Usuario;
    token:   string;
}


export interface GetUsuarios {
    total:    number;
    usuarios: Usuario[];
}

export interface Usuario {
    is_active: boolean;
    rol:       string;
    estado:    boolean;
    couple:    boolean;
    google:    boolean;
    facebook:  boolean;
    nuevo:     boolean;
    nombre:    string;
    correo:    string;
    img?:   string;
    amigos:    any[];
    uid:       string;
}

// Generated by https://quicktype.io

export interface UsuarioSearch {
    results: ResultSearch[];
}

export interface ResultSearch {
    amigos:    any[];
    is_active: boolean;
    couple:    boolean;
    img:       string;
    rol:       string;
    estado:    boolean;
    google:    boolean;
    facebook:  boolean;
    nuevo:     boolean;
    nombre:    string;
    correo:    string;
    uid:       string;
    
}
